-
  name: 'RSS Feed'
  uriPattern: '{node}rss.xml'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'xml'
  routeParts:
    'node':
      handler: 'TYPO3\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: TRUE
