TYPO3:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 1
      inspector:
        editors:
          # by default, only allow to reference Page and its subtypes. Otherwise, all Package Node Types are reachable
          # as well (which makes it hard for editors to find the correct nodes)
          'TYPO3.Neos/Inspector/Editors/LinkEditor':
            editorOptions:
              nodeTypes: ['TYPO3.Neos.NodeTypes:Page']

    nodeTypes:
      groups:
        special:
          position: 'after general'
          label: 'Special'

  TYPO3CR:
    Search:
      # disable realtime search-index updating, as many bugs during publishing appear because of Elasticsearch
      # being down etc.
      realtimeIndexing:
        enabled: false

      # We only need searching for the Neos Marketplace; thus disabling the indexing functionality for user workspaces
      # drastically reduces index size and speeds up indexing.
      indexAllWorkspaces: false

  TypoScript:
    defaultContext:
      Data: 'Neos\NeosIo\Eel\Helper\DataHelper'

Neos:
  NeosIo:
    googleAnalyticsTrackingCode: null
    fundingApi:
      username: ''
      password: ''
      apiUrl: 'https://neosfunding.sandstorm.de'
      timeout: 30
      actions:
        getBadges: '/funding-api-sold-badges'
      parameters: []
