TYPO3:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 1

    nodeTypes:
      groups:
        special:
          position: 'after general'
          label: 'Special'
