version: '2.1'

volumes:
  application: ~

services:

  webserver:
    image: ${BEACH_DEV_WEBSERVER_IMAGE}
    container_name: ${BEACH_DEV_PROJECT_NAME}_webserver_1
    ports:
      - "${BEACH_DEV_WEBSERVER_PORT}:80"
    volumes:
      - application:/application
    depends_on:
      database:
        condition: service_healthy
    links:
      - php
    environment:
      - BEACH_PHP_FPM_HOST=php
      - BEACH_FLOW_BASE_CONTEXT=${BEACH_FLOW_BASE_CONTEXT}
      - BEACH_DATABASE_HOST=${BEACH_DATABASE_HOST}
      - BEACH_DATABASE_PORT=${BEACH_DATABASE_PORT}
      - BEACH_DATABASE_NAME=${BEACH_DATABASE_NAME}
      - BEACH_DATABASE_USERNAME=${BEACH_DATABASE_USERNAME}
      - BEACH_DATABASE_PASSWORD=${BEACH_DATABASE_PASSWORD}

  php:
    image: ${BEACH_DEV_PHP_IMAGE}
    container_name: ${BEACH_DEV_PROJECT_NAME}_php_1
    links:
      - database
    volumes:
      - application:/application
    depends_on:
      database:
        condition: service_healthy
    environment:
      - BEACH_FLOW_BASE_CONTEXT=${BEACH_FLOW_BASE_CONTEXT}
      - BEACH_SITE_URI_SCHEME=${BEACH_SITE_URI_SCHEME}
      - BEACH_SITE_PRIMARY_DOMAIN=${BEACH_SITE_PRIMARY_DOMAIN}
      - BEACH_SITE_BASE_URI=${BEACH_SITE_BASE_URI}
      - BEACH_DATABASE_HOST=${BEACH_DATABASE_HOST}
      - BEACH_DATABASE_PORT=${BEACH_DATABASE_PORT}
      - BEACH_DATABASE_NAME=${BEACH_DATABASE_NAME}
      - BEACH_DATABASE_USERNAME=${BEACH_DATABASE_USERNAME}
      - BEACH_DATABASE_PASSWORD=${BEACH_DATABASE_PASSWORD}
      - BEACH_PHP_FPM_ENABLE=true
      - BEACH_PHP_MEMORY_LIMIT=750M
      - BEACH_ELASTICSEARCH_HOSTNAME=${BEACH_ELASTICSEARCH_HOSTNAME}
      - BEACH_ELASTICSEARCH_PORT=${BEACH_ELASTICSEARCH_PORT}
      - BEACH_ELASTICSEARCH_INDEX_NAME=${BEACH_ELASTICSEARCH_INDEX_NAME}
      - CROWD_API_USERNAME=${CROWD_API_USERNAME}
      - CROWD_API_PASSWORD=${CROWD_API_PASSWORD}

  sidecar:
    image: ${BEACH_DEV_PHP_IMAGE}
    container_name: ${BEACH_DEV_PROJECT_NAME}_sidecar_1
    links:
      - database
    ports:
     - "${BEACH_DEV_SSH_PORT}:22"
    volumes:
      - application:/application
      - ./.Docker/secrets:/secrets
    depends_on:
      database:
        condition: service_healthy
    environment:
      - BEACH_SIDECAR_ENABLE=true
      - BEACH_REMOTE_ENABLE=true
      - BEACH_FLOW_BASE_CONTEXT=${BEACH_FLOW_BASE_CONTEXT}
      - BEACH_SITE_URI_SCHEME=${BEACH_SITE_URI_SCHEME}
      - BEACH_SITE_PRIMARY_DOMAIN=${BEACH_SITE_PRIMARY_DOMAIN}
      - BEACH_SITE_BASE_URI=${BEACH_SITE_BASE_URI}
      - BEACH_DATABASE_HOST=${BEACH_DATABASE_HOST}
      - BEACH_DATABASE_PORT=${BEACH_DATABASE_PORT}
      - BEACH_DATABASE_NAME=${BEACH_DATABASE_NAME}
      - BEACH_DATABASE_USERNAME=${BEACH_DATABASE_USERNAME}
      - BEACH_DATABASE_PASSWORD=${BEACH_DATABASE_PASSWORD}
      - BEACH_REMOTE_AUTHORIZED_KEYS=${BEACH_REMOTE_AUTHORIZED_KEYS}
      - BEACH_PHP_MEMORY_LIMIT=750M
      - BEACH_ELASTICSEARCH_HOSTNAME=${BEACH_ELASTICSEARCH_HOSTNAME}
      - BEACH_ELASTICSEARCH_PORT=${BEACH_ELASTICSEARCH_PORT}
      - BEACH_ELASTICSEARCH_INDEX_NAME=${BEACH_ELASTICSEARCH_INDEX_NAME}
      - CROWD_API_USERNAME=${CROWD_API_USERNAME}
      - CROWD_API_PASSWORD=${CROWD_API_PASSWORD}

  database:
    image: mariadb:10.1
    container_name: ${BEACH_DEV_PROJECT_NAME}_database_1
    volumes:
      - ./.Docker/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${BEACH_DATABASE_PASSWORD}
      - MYSQL_DATABASE=${BEACH_DATABASE_NAME}
    ports:
       - ${BEACH_DEV_DATABASE_PORT}:${BEACH_DATABASE_PORT}
    command: 'mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci'
    healthcheck:
      test: "echo 'SELECT 0;' | mysql -u ${BEACH_DATABASE_USERNAME} --password=${BEACH_DATABASE_PASSWORD}"
      interval: 1s
      timeout: 5s
      retries: 120

  elasticsearch:
    image: elasticsearch:1.7.5
    container_name: ${BEACH_DEV_PROJECT_NAME}_elasticsearch_1
    volumes:
      - ./.Docker/elasticsearch:/data
    ports:
       - ${BEACH_DEV_ELASTICSEARCH_PORT}:9200
#    healthcheck:
#      test: "..."
#      interval: 1s
#      timeout: 5s
#      retries: 120
