SwiftMailer:
  transport:
    type: 'Swift_SmtpTransport'
    options:
      host: '%env:SMTP_HOST%'
      # Should come from env var SMTP_PORT but that doesn't work yet as it needs to be an int
      port: 587
      encryption: 'ssl'
      username: '%env:SMTP_USERNAME%'
      password: '%env:SMTP_PASSWORD%'
