Neos:
  Seo:
    robotsTxt:
      excludedDimensionsPresets:
        - de
    twitterCard:
      siteHandle: '@neoscms'
    facebook:
      profileId: 'NeosCMS'
    socialProfile:
      type: 'Organization'
      logo: 'resource://Neos.NeosIo/Public/Images/NeosLogoSocial.png'
      profiles:
        twitter: 'neoscms'
        facebook: 'NeosCMS'
        instagram: 'neoscms'
        youTube: 'UCQndryIh2s9i3htDrpb6tiw'
