
Neos:
  Neos:
    fusion:
      autoInclude:
        Neos.NeosIo.ServiceOfferings: true

    nodeTypes:
      groups:
        serviceOfferings:
          position: 'after general'
          label: 'Service offerings'
