#                                                                        #
# Routes configuration                                                   #

##
# Flowpack SearchPlugin sub routes

-
  name: 'FlowpackSearchPlugin'
  uriPattern: '<FlowpackSearchPluginSubRoutes>'
  subRoutes:
    FlowpackSearchPluginSubRoutes:
      package: Flowpack.SearchPlugin
      variables:
        'defaultUriSuffix': '.html'

##
# Neos Seo: XML sitemap

-
  name: 'Neos Seo'
  uriPattern: '<NeosSeoSubRoutes>'
  subRoutes:
    'NeosNeosSeoSubRoutes':
      package: 'Neos.Seo'
      variables:
        'xmlSitemapPath': 'sitemap.xml'

##
# Ttree OutOfBandRendering sub routes
-
  name: 'Ttree.OutOfBandRendering'
  uriPattern: '<TtreeOutOfBandRenderingSubRoutes>'
  subRoutes:
    'TtreeOutOfBandRenderingSubRoutes':
      package: 'Ttree.OutOfBandRendering'
      variables:
        'defaultUriSuffix': ''

-
  name: 'neos.io'
  uriPattern: '<NeosIoSubRoutes>'
  subRoutes:
    'NeosIoSubRoutes':
      package: 'Neos.NeosIo'

##
# Neos sub routes
-
  name: 'NeosNeos'
  uriPattern: '<NeosNeosSubRoutes>'
  subRoutes:
    NeosNeosSubRoutes:
      package: Neos.Neos
      variables:
        'defaultUriSuffix': '.html'
