#                                                                        #
# Routes configuration                                                   #

##
# Ttree OutOfBandRendering sub routes
-
  name: 'Ttree.OutOfBandRendering'
  uriPattern: '<TtreeOutOfBandRenderingSubRoutes>'
  subRoutes:
    'TtreeOutOfBandRenderingSubRoutes':
      package: 'Ttree.OutOfBandRendering'
      variables:
        'defaultUriSuffix': ''

-
  name: 'neos.io'
  uriPattern: '<NeosIoSubRoutes>'
  subRoutes:
    'NeosIoSubRoutes':
      package: 'Neos.NeosIo'

##
# Neos sub routes
-
  name: 'NeosNeos'
  uriPattern: '<NeosNeosSubRoutes>'
  subRoutes:
    NeosNeosSubRoutes:
      package: Neos.Neos
      variables:
        'defaultUriSuffix': '.html'
