#                                                                        #
# Routes configuration                                                   #

##
# Flowpack SearchPlugin subroutes

-
  name: 'FlowpackSearchPlugin'
  uriPattern: '<FlowpackSearchPluginSubroutes>'
  subRoutes:
    FlowpackSearchPluginSubroutes:
      package: Flowpack.SearchPlugin
      variables:
        'defaultUriSuffix': '.html'

##
# Ttree OutOfBandRendering subroutes
-
  name: 'Ttree.OutOfBandRendering'
  uriPattern: '<TtreeOutOfBandRenderingSubroutes>'
  subRoutes:
    'TtreeOutOfBandRenderingSubroutes':
      package: 'Ttree.OutOfBandRendering'
      variables:
        'defaultUriSuffix': ''

##
# TYPO3 Neos subroutes

-
  name: 'TYPO3Neos'
  uriPattern: '<TYPO3NeosSubroutes>'
  subRoutes:
    TYPO3NeosSubroutes:
      package: TYPO3.Neos
      variables:
        'defaultUriSuffix': '.html'
