##
# RobertLemke Blog plugin

-
  name: 'RobertLemkeBlogPlugin'
  uriPattern: 'news/<RobertLemkeBlogPluginSubroutes>'
  subRoutes:
    RobertLemkeBlogPluginSubroutes:
      package: RobertLemke.Plugin.Blog

##
# TYPO3 Neos subroutes

-
  name: 'TYPO3Neos'
  uriPattern: '<TYPO3NeosSubroutes>'
  subRoutes:
    TYPO3NeosSubroutes:
      package: TYPO3.Neos
      variables:
        'defaultUriSuffix': '.html'