#                                                                        #
# Routes configuration                                                   #

##
# Flowpack SearchPlugin subroutes

-
  name: 'FlowpackSearchPlugin'
  uriPattern: '<FlowpackSearchPluginSubroutes>'
  subRoutes:
    FlowpackSearchPluginSubroutes:
      package: Flowpack.SearchPlugin
      variables:
        'defaultUriSuffix': '.html'

##
# TYPO3 Neos Seo: XML Sitemap

-
  name: 'TYPO3 Neos Seo'
  uriPattern: '<TYPO3NeosSeoSubroutes>'
  subRoutes:
    'TYPO3NeosSeoSubroutes':
      package: 'TYPO3.Neos.Seo'
      variables:
        'xmlSitemapPath': 'sitemap.xml'

##
# Ttree OutOfBandRendering subroutes
-
  name: 'Ttree.OutOfBandRendering'
  uriPattern: '<TtreeOutOfBandRenderingSubroutes>'
  subRoutes:
    'TtreeOutOfBandRenderingSubroutes':
      package: 'Ttree.OutOfBandRendering'
      variables:
        'defaultUriSuffix': ''

-
  name: 'neos.io'
  uriPattern: '<NeosIoSubroutes>'
  subRoutes:
    'NeosIoSubroutes':
      package: 'Neos.NeosIo'

##
# TYPO3 Neos subroutes

-
  name: 'TYPO3Neos'
  uriPattern: '<TYPO3NeosSubroutes>'
  subRoutes:
    TYPO3NeosSubroutes:
      package: TYPO3.Neos
      variables:
        'defaultUriSuffix': '.html'
