
TYPO3:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: neos_io
        user: root
        password: test
        host: 127.0.0.1
