#
# Development settings for dev.neos.io
#

Neos:
  Flow:
    persistence:
      backendOptions:
        host: '%env:BEACH_DATABASE_HOST%'
        dbname: '%env:BEACH_DATABASE_NAME%'
        user: '%env:BEACH_DATABASE_USERNAME%'
        password: '%env:BEACH_DATABASE_PASSWORD%'
        unix_socket: '%env:BEACH_DATABASE_SOCKET%'

    http:
      baseUri: '%env:BEACH_SITE_BASE_URI%'

  Imagine:
    driver: 'Imagick'
