#
# Settings used for development in Local Beach
#

Neos:
  Flow:
    persistence:
      backendOptions:
        host: '%env:BEACH_DATABASE_HOST%'
        dbname: '%env:BEACH_DATABASE_NAME%'
        user: '%env:BEACH_DATABASE_USERNAME%'
        password: '%env:BEACH_DATABASE_PASSWORD%'
        port: '%env:BEACH_DATABASE_PORT%'

  NeosIo:
    crowdApi:
      username: '%env:CROWD_API_USERNAME%'
      password: '%env:CROWD_API_PASSWORD%'

  MarketPlace:
    github:
      token: '%env:GITHUG_API_TOKEN%'

Flowpack:
  ElasticSearch:
    clients:
      default:
        - host: '%env:ELASTICSEARCH_HOSTNAME%'
          port: 9200
          username: '%env:ELASTICSEARCH_USERNAME%'
          password: '%env:ELASTICSEARCH_PASSWORD%'

    indexes:
      default:
        'wwwneosio-development':
          settings:
            analysis:
              filter:
                autocompleteFilter:
                  max_shingle_size: 4
                  min_shingle_size: 2
                  type: 'shingle'
              analyzer:
                autocomplete:
                  filter: [ 'lowercase', 'autocompleteFilter' ]
                  char_filter: [ 'html_strip' ]
                  type: 'custom'
                  tokenizer: 'standard'

    ContentRepositoryAdaptor:
      driver:
        version: '7.x'

  FullPageCache:
    # disable full page caching
    enabled: false
