Neos:
  GoogleAnalytics:
    sites:
      'neosio':
        trackingId: 'UA-57276307-4'
        profileId: '120499365'
      'neosconio':
        trackingId: 'UA-57276307-4'
        profileId: '120499365'
      'flowneosio':
        trackingId: 'UA-57276307-4'
        profileId: '120499365'
